#!/bin/bash

# autostart
bash $HOME/.config/bspwm/scripts/autostart.sh

# uncomment to use monitor setup
# bash $HOME/.config/bspwm/scripts/monitor.sh

function setopt () {
  bspc config "$1" "$2"
}

# borders and gaps
setopt border_width 0
setopt window_gap 12

# behaviour stuff
setopt split_ratio 0.52
setopt borderless_monocle true
setopt gapless_monocle true
setopt single_monocle false

# pointer
setopt focus_follows_pointer true
setopt pointer_follows_focus true
setopt pointer_follows_monitor true

# plank compatibility
bspc rule -a Plank layer=above manage=on border=off
